#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec  3 17:19:43 2017

@author: elijahbarnes
"""

import numpy as np
import pylab as py

M = 100
error = 1
delta = 1e-6
def Rho(x,y):
    c = 0
    if (x>= 20 and x<= 40) and (y>= 60 and y<= 80):
        c = 1
    if (x>= 60 and x<= 80) and (y>= 20 and y<= 40):
        c = -1
    return c

Phi = np.zeros([M,M],float)
Phi_prime = Phi

while error > delta:
    for x in range(0,M):
        for y in range(0,M):
            if x == 0 or y == 0 or x == M-1 or y == M-1:
                Phi_prime[x,y] = Phi[x,y]
            else:
                Phi_prime[x,y] = (Phi[x+1,y] + Phi[x,y+1] + Phi[x,y-1] + Phi[x-1,y])/4
                Phi_prime[x,y] = Phi_prime[x,y]+(.01**2/4)*(Rho(x,y))
            error = np.max(np.abs(Phi-Phi_prime))
        Phi,Phi_prime = Phi_prime,Phi
        
py.imshow(Phi)
py.show()
            
        