#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 20 08:09:54 2017

@author: elijahbarnes
"""

import numpy as np

r_EtoL1 = 100
R_EtoM = 3.844e8
G = 6.674e-11
omega = 2.662e-6
m_moon = 7.348e22
M_earth = 5.874e24

def g(r):
    return (1/(omega*omega))*(G*M_earth/(r*r)- G*m_moon/((R_EtoM-r)**(2)))
def Dg(r):
    return (1/(omega*omega))*(-2*G*M_earth/(r*r*r)-2*G*m_moon/((R_EtoM-r)**(3)))
    
error = 1000
delta = 1

while error > delta:
   r = r_EtoL1 - g(r_EtoL1)/Dg(r_EtoL1)
   error = np.abs(r-r_EtoL1)
   r_EtoL1 = r

print ("The Langrange point is at",r)