#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Oct  2 16:54:17 2017

@author: elijahbarnes
"""

import numpy as np
from pylab import imshow, show

Epsilon = 8.854187817e-12


def V(a,x,y,z):
    return (1/(4*np.pi*Epsilon))*(5*np.sin(a)**(2) + 4)**(.5)/(((x-3*np.cos(a))**(2)+(y-2*np.sin(a))**(2)+(z**(2)))**(.5))


x = np.arange (-3,3,.1)
y = np.arange (-3,3,.1)
z = 1

def SimpV(a,x,y,z):
    b = 2*np.pi
    h = .1
    S1 = 0
    S2 = 0
    N = int((b)/h)
    
    for k in range (1,N,2):
        S1+= V(k*h,x,y,z)

    for n in range (2,N,2):
        S2+= V(n*h,x,y,z)
    
    return h/3*(V(0,x,y,z)+V(2*np.pi,x,y,z)+ 4*S1 + 2*S2)

a = 0
b = 0
L = len(x)
T = np.empty([L,L],float)
t = np.arange(0,2*np.pi,.1)

for a in range(L):
    for b in range(L):
        T[a,b] = SimpV(t,x[a],x[b],z)
        b+=1
    a+=1
imshow(T,origin="lower",extent=[-2,2,-2,2])

show()